stages:
  - build
  - test
  - upload

build-amd64-debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_jessie/
    - mv ../*.deb built-packages/amd64/debian_jessie/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-stretch:
  stage: build
  image: debian:stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_stretch/
    - mv ../*.deb built-packages/amd64/debian_stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-xenial:
  stage: build
  image: ubuntu:xenial
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_xenial/
    - mv ../*.deb built-packages/amd64/ubuntu_xenial/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_bionic/
    - mv ../*.deb built-packages/amd64/ubuntu_bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-cosmic:
  stage: build
  image: ubuntu:cosmic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_cosmic/
    - mv ../*.deb built-packages/amd64/ubuntu_cosmic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-29:
  stage: build
  image: fedora:29
  script:
    - ./gitlab-build-rpm.sh fedora29
    - mkdir -p built-packages/amd64/fedora_29/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/amd64/fedora_29/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-28:
  stage: build
  image: fedora:28
  script:
    - ./gitlab-build-rpm.sh fedora28
    - mkdir -p built-packages/amd64/fedora_28/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/amd64/fedora_28/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-centos7:
  stage: build
  image: centos:7
  script:
    - ./gitlab-build-rpm.sh centos7
    - mkdir -p built-packages/amd64/centos_7/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/amd64/centos_7/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-centos6:
  stage: build
  image: centos:6
  script:
    - ./gitlab-build-rpm.sh centos6
    - mkdir -p built-packages/amd64/centos_6/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/amd64/centos_6/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

run-unit-tests-ubuntu-xenial:
  stage: test
  image: ubuntu:xenial
  script:
    - ./run-tests.sh ubuntu_xenial
  only:
    - tags

run-unit-tests-ubuntu-bionic:
  stage: test
  image: ubuntu:bionic
  script:
    - ./run-tests.sh ubuntu_bionic
  only:
    - tags

run-unit-tests-ubuntu-cosmic:
  stage: test
  image: ubuntu:cosmic
  script:
    - ./run-tests.sh ubuntu_cosmic
  only:
    - tags

run-unit-tests-debian-stretch:
  stage: test
  image: debian:stretch
  script:
    - ./run-tests.sh debian_stretch
  only:
    - tags

run-unit-tests-debian-jessie:
  stage: test
  image: debian:jessie
  script:
    - ./run-tests.sh debian_jessie
  only:
    - tags

upload-packages:
  stage: upload
  image: ubuntu:bionic
  script:
    - ./bintray-upload.sh
  only:
    - tags
