stages:
  - build
  - test
  - upload

build-amd64-debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/jessie/
    - mv ../*.deb built-packages/jessie/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-stretch:
  stage: build
  image: debian:stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/stretch/
    - mv ../*.deb built-packages/stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/buster/
    - mv ../*.deb built-packages/buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-xenial:
  stage: build
  image: ubuntu:xenial
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/xenial/
    - mv ../*.deb built-packages/xenial/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/bionic/
    - mv ../*.deb built-packages/bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-eoan:
  stage: build
  image: ubuntu:eoan
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/eoan/
    - mv ../*.deb built-packages/eoan/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-ubuntu-focal:
  stage: build
  image: ubuntu:focal
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/focal/
    - mv ../*.deb built-packages/focal/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-29:
  stage: build
  image: fedora:29
  script:
    - ./gitlab-build-rpm.sh fedora29
    - mkdir -p built-packages/fedora_29/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_29/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-30:
  stage: build
  image: fedora:30
  script:
    - ./gitlab-build-rpm.sh fedora30
    - mkdir -p built-packages/fedora_30/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_30/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-31:
  stage: build
  image: fedora:31
  script:
    - ./gitlab-build-rpm.sh fedora31
    - mkdir -p built-packages/fedora_31/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_31/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-fedora-32:
  stage: build
  image: fedora:32
  script:
    - ./gitlab-build-rpm.sh fedora32
    - mkdir -p built-packages/fedora_32/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/fedora_32/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-centos8:
  stage: build
  image: centos:8
  script:
    - ./gitlab-build-rpm.sh centos8
    - mkdir -p built-packages/centos_8/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/centos_8/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

build-amd64-centos7:
  stage: build
  image: centos:7
  script:
    - ./gitlab-build-rpm.sh centos7
    - mkdir -p built-packages/centos_7/
    - mv ~/rpmbuild/RPMS/x86_64/*.rpm built-packages/centos_7/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day
  only:
    - tags

run-unit-tests-ubuntu-xenial:
  stage: test
  image: ubuntu:xenial
  script:
    - ./run-tests.sh xenial
  only:
    - tags

run-unit-tests-ubuntu-bionic:
  stage: test
  image: ubuntu:bionic
  script:
    - ./run-tests.sh bionic
  only:
    - tags

run-unit-tests-ubuntu-cosmic:
  stage: test
  image: ubuntu:cosmic
  script:
    - ./run-tests.sh cosmic
  only:
    - tags

run-unit-tests-ubuntu-disco:
  stage: test
  image: ubuntu:disco
  script:
    - ./run-tests.sh disco
  only:
    - tags

run-unit-tests-ubuntu-eoan:
  stage: test
  image: ubuntu:eoan
  script:
    - ./run-tests.sh eoan
  only:
    - tags

run-unit-tests-debian-stretch:
  stage: test
  image: debian:stretch
  script:
    - ./run-tests.sh stretch
  only:
    - tags

run-unit-tests-debian-jessie:
  stage: test
  image: debian:jessie
  script:
    - ./run-tests.sh jessie
  only:
    - tags

run-unit-tests-debian-buster:
  stage: test
  image: debian:buster
  script:
    - ./run-tests.sh buster
  only:
    - tags

run-unit-tests-fedora-29:
  stage: test
  image: fedora:29
  script:
    - ./run-tests-rpm.sh fedora_29
  only:
    - tags

run-unit-tests-fedora-30:
  stage: test
  image: fedora:30
  script:
    - ./run-tests-rpm.sh fedora_30
  only:
    - tags

run-unit-tests-centos-6:
  stage: test
  image: centos:6
  script:
    - ./run-tests-rpm.sh centos_6
  only:
    - tags

run-unit-tests-centos-7:
  stage: test
  image: centos:7
  script:
    - ./run-tests-rpm.sh centos_7
  only:
    - tags

run-unit-tests-centos-8:
  stage: test
  image: centos:8
  script:
    - ./run-tests-rpm.sh centos_8
  only:
    - tags

upload-packages:
  stage: upload
  image: ubuntu:bionic
  script:
    - ./bintray-upload.sh
  only:
    - tags
